export const Users = [
    {
      id:1,
      profilePicture: "/assets/person/1.jpg",
      username: "Samihan Nandedkar",
    },
    {
      id:2,
      profilePicture: "/assets/person/2.png",
      username: "PersonOne Friend",
    },
    {
      id:3,
      profilePicture: "/assets/person/3.png",
      username: "PersonTwo Friend",
    },
    {
      id:4,
      profilePicture: "/assets/person/4.png",
      username: "PersonThree Friend",
    },
    {
      id:5,
      profilePicture: "/assets/person/5.png",
      username: "PersonFour Friend",
    },
    {
      id:6,
      profilePicture: "/assets/person/6.png",
      username: "PersonFive Friend",
    },
    {
      id:7,
      profilePicture: "/assets/person/7.jpg",
      username: "PersonSix Friend",
    },
    {
      id:8,
      profilePicture: "/assets/person/8.png",
      username: "PersonSeven Friend",
    },
    {
      id:9,
      profilePicture: "/assets/person/9.png",
      username: "PersonEight Friend",
    },
    {
      id:10,
      profilePicture: "/assets/person/10.png",
      username: "PersonNine Friend",
    },
  ];


  export const Posts = [
    {
      id: 1,
      desc: "Hello. This sample introductory post",
      photo: "/assets/post/1.png",
      date: "2 mins ago",
      userId: 1,
      like: 0,
      comment: 0,
    },
    {
      id: 2,
      desc: "Chicago, Like never before",
      photo: "/assets/post/2.png",
      date: "15 mins ago",
      userId: 2,
      like: 0,
      comment: 0,
    },
    {
      id: 3,
      desc: "`By dint of building well, you get to be a good architect` - Aristotle",
      photo: "/assets/post/3.png",
      date: "1 hour ago",
      userId: 3,
      like: 0,
      comment: 0,
    },
    {
      id: 4,
      photo: "/assets/post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 0,
      comment: 0,
    },
    {
      id: 5,
      photo: "/assets/post/5.png",
      date: "5 hours ago",
      userId: 5,
      like: 0,
      comment: 0,
    },
    {
      id: 6,
      photo: "/assets/post/6.png",
      date: "1 day ago",
      userId: 6,
      like: 0,
      comment: 0,
    },
    {
      id: 7,
      desc: "The Windy City!",
      photo: "/assets/post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 0,
      comment: 0,
    },
    {
      id: 8,
      photo: "/assets/post/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 0,
      comment: 0,
    },
    {
      id: 9,
      desc: "`Going to Chicago was like going out of the world.` —Muddy Waters",
      photo: "/assets/post/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 0,
      comment: 0,
    },
    {
      id: 10,
      photo: "/assets/post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 0,
      comment: 0,
    },
  ];